version: "3"
services:
    standalone:
        image: minikube-kompose:v1
        build:
            context: ./app
            dockerfile: ./Dockerfile
        ports:
            - 1234:1234
    kubernetes:
        image: quay.io/aspenmesh/minikube-dind
        privileged: true
        ports:
            - 8443:8443
